# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
