# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 2
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.cache/wt [current_project]
set_property parent.project_path C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files c:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject_Team1/coe_maker/BlackBox.coe
read_verilog -library xil_defaultlib {
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/TOP_VGA.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/VGA_mem_top.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/VGA_module.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/add_32.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/alarm.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/async_fifo.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/cam_capture.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/cam_config.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/cam_init.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/cam_rom.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/cam_top.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/clkgen_200KHz.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/conv.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/debouncer.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/divide_by_5.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/grayscale.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/i2c_master.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/linebuffer.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/mem_bram.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/mem_top.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/multiply_by_9.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/sccb_master.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/seg7c.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/sync_fifo.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/temp_converter.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/top_cam.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/top_temp.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/top_user_control.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/top_vgm.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/vga_data.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/vga_display.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/vga_driver.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/vga_top.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/vp_control.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/vp_top.v
  C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/new/top.v
}
read_ip -quiet c:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet c:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
set_property used_in_implementation false [get_files -all c:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.gen/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.gen/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.gen/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc]

read_ip -quiet c:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/constrs_1/new/Nexys-A7-100T.xdc
set_property used_in_implementation false [get_files C:/Users/ddoihyun/24-2/DigitalSystemDesign/Projects/DSD_FinalProject/DSD_FinalProject_Temp_Camera_revised.srcs/constrs_1/new/Nexys-A7-100T.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
